---
services:

  sngrep:
    image: crpi-36qq8mv72daqudw8.cn-guangzhou.personal.cr.aliyuncs.com/flycun/sngrep
    container_name: sngrep
    privileged: true  
    network_mode: host 
    environment:
      - TERM=xterm
    cap_add:
      - NET_ADMIN

  kamailio-edge:
    image: crpi-36qq8mv72daqudw8.cn-guangzhou.personal.cr.aliyuncs.com/flycun/kamailio-ci:5.4-alpine.debug
    container_name: kamailio-edge
    ports:
      - "5087:5060/udp"
      - "5099:5061/udp"
    volumes:
      - ./kamailio-default/etc/kamailio/:/etc/kamailio
      - ./kamailio-default/etc/resolv.conf:/etc/resolv.conf
    environment:
      - KAM_SHM_MEM_SIZE=256
      - COREIP=172.16.254.2
      - CORESUBNET=172.16.254.1/24
      - TLSPORT=5061
      - UDPPORT=5060
      - PUBLICIP=192.168.254.2
      - DBUSERNAME=kamailio
      - DBPASSWORD=kamailiorw
      - DBHOST=172.16.254.10
      - DBNAME=kamailio
    depends_on:
      rtpengine-edge:
        condition: service_started
      db:
        condition: service_started
    dns:
      - 172.16.254.20
    networks:
      kamailio-external:
        ipv4_address: 192.168.254.2
      kamailio-internal:
        ipv4_address: 172.16.254.2

  rtpengine-edge:
    image: crpi-36qq8mv72daqudw8.cn-guangzhou.personal.cr.aliyuncs.com/flycun/rtpengine:edge
    container_name: rtpengine-edge
    ports:
      - "23000-23100:23000-23100"
    volumes:
      - ./rtpengine-edge/config:/etc/rtpengine
    networks:
      kamailio-external:
        ipv4_address: 192.168.254.3
      kamailio-internal:
        ipv4_address: 172.16.254.3


  b2bua_internal_01:
    tty: true
    container_name: b2bua_internal_01 
    stdin_open: true
    volumes:
      - ./b2bua/b2bua_internal_01/:/config
    command: pjsua --config-file=/config/pjsua.cfg
    image: crpi-36qq8mv72daqudw8.cn-guangzhou.personal.cr.aliyuncs.com/flycun/pjsua:latest
    ports:
      - "5091:5060"
    networks:
      kamailio-internal:
        ipv4_address: 172.16.254.101
    depends_on:
      kamailio-edge:
        condition: service_started

  b2bua_internal_02:
    tty: true
    container_name: b2bua_internal_02 
    stdin_open: true
    volumes:
      - ./b2bua/b2bua_internal_02/:/config
    command: pjsua --config-file=/config/pjsua.cfg
    image: crpi-36qq8mv72daqudw8.cn-guangzhou.personal.cr.aliyuncs.com/flycun/pjsua:latest
    ports:
      - "5092:5060"
    networks:
      kamailio-internal:
        ipv4_address: 172.16.254.102
    depends_on:
      kamailio-edge:
        condition: service_started

  b2bua_external_01:
    tty: true
    container_name: b2bua_external_01
    stdin_open: true
    volumes:
      - ./b2bua/b2bua_external_01/:/config
    image: crpi-36qq8mv72daqudw8.cn-guangzhou.personal.cr.aliyuncs.com/flycun/pjsua:latest
    command: pjsua --config-file=/config/pjsua.cfg
    #command: "tail -f /dev/null"
    ports:
      - "5093:5060"
    networks:
      kamailio-external:
        ipv4_address: 192.168.254.101
    depends_on:
      kamailio-edge:
        condition: service_started

  b2bua_external_02:
    tty: true
    container_name: b2bua_external_02
    stdin_open: true
    volumes:
      - ./b2bua/b2bua_external_02/:/config
    image: crpi-36qq8mv72daqudw8.cn-guangzhou.personal.cr.aliyuncs.com/flycun/pjsua:latest
    command: pjsua --config-file=/config/pjsua.cfg
    #command: "tail -f /dev/null"
    ports:
      - "5094:5060"
    networks:
      kamailio-external:
        ipv4_address: 192.168.254.102
    depends_on:
      kamailio-edge:
        condition: service_started

  db:
    image: crpi-36qq8mv72daqudw8.cn-guangzhou.personal.cr.aliyuncs.com/flycun/mysql:5.7
    restart: always
    container_name: db01
    environment:
      MYSQL_DATABASE: 'kamailio'
      MYSQL_USER: 'kamailio'
      MYSQL_PASSWORD: 'kamailioro'
      MYSQL_ROOT_PASSWORD: 'kamailio2025'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      kamailio-internal:
        ipv4_address: 172.16.254.10

  bind:
    image: crpi-36qq8mv72daqudw8.cn-guangzhou.personal.cr.aliyuncs.com/flycun/bind9:9.20
    container_name: bind
    ports:
      - "531:53/udp"
      - "531:53/tcp"
    volumes:
      - ./bind/named.conf:/etc/bind/named.conf
      - ./bind/named.conf.local:/etc/bind/named.conf.local
      - ./bind/db.e164.arpa:/etc/bind/db.e164.arpa
    restart: always
    networks:
      kamailio-internal:
        ipv4_address: 172.16.254.20

  api:
    container_name: api
    image: crpi-36qq8mv72daqudw8.cn-guangzhou.personal.cr.aliyuncs.com/flycun/kamailio-course-api
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./api/app:/app
    networks:
      kamailio-internal:
        ipv4_address: 172.16.254.30

networks:
  kamailio-external:
    external: true
  kamailio-internal:
    external: true
